if(NOT DAWN_ROOT)
  message(FATAL_ERROR "Pass -DDAWN_ROOT=<pinned checkout>; tools/bootstrap-dawn.ps1 provisions it explicitly")
endif()
execute_process(COMMAND git -C "${DAWN_ROOT}" rev-parse HEAD OUTPUT_VARIABLE DAWN_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT DAWN_COMMIT STREQUAL "34b1fca4d6c3d7025a2231d82b4fc719ca57fd71")
  message(FATAL_ERROR "Dawn commit mismatch")
endif()
set(DAWN_BUILD_DIR "${DAWN_ROOT}/out/framebridge-relwithdebinfo" CACHE PATH "Explicit Dawn build directory")
file(GLOB_RECURSE DAWN_STATIC_LIBS CONFIGURE_DEPENDS "${DAWN_BUILD_DIR}/*.lib")
if(NOT DAWN_STATIC_LIBS OR NOT EXISTS "${DAWN_BUILD_DIR}/gen/include/dawn/webgpu_cpp.h")
  message(FATAL_ERROR "Build pinned Dawn first with tools/bootstrap-dawn.ps1")
endif()
add_library(framebridge-renderer STATIC "${CMAKE_CURRENT_LIST_DIR}/renderer.cpp")
target_compile_features(framebridge-renderer PUBLIC cxx_std_20)
target_compile_definitions(framebridge-renderer PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_include_directories(framebridge-renderer PUBLIC "${CMAKE_CURRENT_LIST_DIR}" "${CMAKE_CURRENT_LIST_DIR}/../mirror-receiver" "${CMAKE_CURRENT_LIST_DIR}/../bridge")
target_include_directories(framebridge-renderer SYSTEM PRIVATE "${DAWN_ROOT}/include" "${DAWN_BUILD_DIR}/gen/include")
target_link_libraries(framebridge-renderer PRIVATE ${DAWN_STATIC_LIBS} d3d12 d3dcompiler dxgi dxguid OneCore)
target_compile_options(framebridge-renderer PRIVATE /W4 /WX /permissive-)
file(GLOB FXC_CANDIDATES "$ENV{WindowsSdkDir}/bin/$ENV{WindowsSDKVersion}/x64/d3dcompiler_47.dll")
if(NOT FXC_CANDIDATES)
  message(FATAL_ERROR "Windows SDK x64 d3dcompiler_47.dll required; configure using tools/msvc-env.ps1")
endif()
list(GET FXC_CANDIDATES 0 FXC_DLL)
configure_file("${FXC_DLL}" "${CMAKE_BINARY_DIR}/d3dcompiler_47.dll" COPYONLY)
