import assert from "node:assert/strict";
import WebSocket from "ws";
import { BridgeServer } from "./server.js";
import { decode, encode, encodeFrameState, MessageType, type FrameState } from "./index.js";

const origin = "http://127.0.0.1:5173"; const server = new BridgeServer(origin); const port = await server.start();
const hello = { kind: "hello", version: 0, token: server.token, origin, three: { version: "0.185.0", commit: "2431a09" }, buildId: "test", requestedCapabilities: ["explicit-mirror"], byteOrder: "little" } as const;
const connect = (): { socket: WebSocket; capabilities: Promise<void>; acks: number[] } => { const socket = new WebSocket(`ws://127.0.0.1:${port}`, { headers: { Origin: origin } }); const acks: number[] = []; const capabilities = new Promise<void>((resolve, reject) => { socket.once("open", () => socket.send(JSON.stringify(hello))); socket.once("message", (data, binary) => { if (binary) return reject(new Error("capabilities not JSON")); assert.equal(JSON.parse(data.toString()).kind, "capabilities"); resolve(); }); socket.once("error", reject); }); socket.on("message", (data, binary) => { if (binary) { const m = decode(new Uint8Array(data as Buffer)); if (m.type === MessageType.FrameAccepted) acks.push(Number(new DataView(m.payload.buffer, m.payload.byteOffset).getBigUint64(8, true))); } }); return { socket, capabilities, acks }; };
const client = connect(); await client.capabilities;
const makeState = (frame: bigint): FrameState => ({ frame, simulationTime: Number(frame) / 60, rotationX: Number(frame) * .01, rotationY: Number(frame) * .013, cameraZ: 3, width: 640, height: 360, resizeGeneration: 0n });
for (let frame = 1n; frame <= 3n; frame++) { client.socket.send(encode({ type: MessageType.BeginFrame, sequence: frame * 2n - 1n, payload: encodeFrameState(makeState(frame)) })); client.socket.send(encode({ type: MessageType.EndFrame, sequence: frame * 2n, payload: new Uint8Array() })); }
await new Promise((resolve) => setTimeout(resolve, 50)); assert.deepEqual(client.acks, [1, 2, 3]); client.socket.close(); await new Promise((resolve) => client.socket.once("close", resolve));
const reconnect = connect(); await reconnect.capabilities; reconnect.socket.send(encode({ type: MessageType.BeginFrame, sequence: 1n, payload: encodeFrameState(makeState(4n)) })); reconnect.socket.send(encode({ type: MessageType.EndFrame, sequence: 2n, payload: new Uint8Array() })); await new Promise((resolve) => setTimeout(resolve, 50)); assert.deepEqual(reconnect.acks, [4]); reconnect.socket.close(); await server.close();
console.log("TCW-PROTO-003_PASS real_loopback_auth_binary_ack_reconnect"); console.log("TCW-CONT-001_PASS browser_authoritative_frame=4 receiver_ack_frame=4"); console.log("TCW-PROTO-004_BLOCKED real_1800_second_soak_not_run_in_short_suite");
