import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { decode, encode, encodeFrameState, MessageType, MirrorSession, MAX_DRAWS_PER_FRAME, type FrameState } from "./index.js";
const state = (frame: bigint): FrameState => ({ frame, simulationTime: Number(frame) / 60, rotationX: Number(frame) * .01, rotationY: Number(frame) * .013, cameraZ: 3, width: 640, height: 360, resizeGeneration: 0n });
const bytes = encode({ type: MessageType.BeginFrame, sequence: 1n, payload: encodeFrameState(state(1n)) }); assert.equal(bytes.length, 84); assert.deepEqual([...decode(bytes).payload], [...bytes.slice(36)]);
const bad = (mutate: (b: Uint8Array) => void): void => { const copy = bytes.slice(); mutate(copy); assert.throws(() => decode(copy)); }; bad(b => new DataView(b.buffer).setUint32(0, 0, true)); bad(b => new DataView(b.buffer).setUint16(4, 1, true)); bad(b => new DataView(b.buffer).setUint16(6, 99, true)); bad(b => new DataView(b.buffer).setUint32(8, 1, true)); bad(b => b.fill(0, 16, 24)); bad(b => new DataView(b.buffer).setUint32(12, 49, true)); bad(b => b[40] = b[40]! ^ 1); assert.throws(() => decode(bytes.slice(0, -1)));
const session = new MirrorSession("fixture-session"); session.accept(decode(bytes)); assert.throws(() => session.accept(decode(encode({ type: MessageType.BeginFrame, sequence: 2n, payload: encodeFrameState(state(1n)) })))); session.accept(decode(encode({ type: MessageType.EndFrame, sequence: 3n, payload: new Uint8Array() }))); assert.equal(session.processOne()?.frame, 1n); assert.throws(() => session.accept(decode(encode({ type: MessageType.EndFrame, sequence: 4n, payload: new Uint8Array() }))));
const resource = new Uint8Array(8); new DataView(resource.buffer).setBigUint64(0, 4096n, true); const resourceSession = new MirrorSession("resources"); resourceSession.accept(decode(encode({ type: MessageType.CreateBuffer, sequence: 1n, objectId: 7n, payload: resource }))); assert.equal(resourceSession.declaredResourceBytes, 4096); resourceSession.accept(decode(encode({ type: MessageType.DestroyResource, sequence: 2n, objectId: 7n, payload: new Uint8Array() }))); assert.equal(resourceSession.declaredResourceBytes, 0);
const queued = new MirrorSession("queue"); for (let i = 1n; i <= 3n; i++) { queued.accept(decode(encode({ type: MessageType.BeginFrame, sequence: i * 2n - 1n, payload: encodeFrameState(state(i)) }))); queued.accept(decode(encode({ type: MessageType.EndFrame, sequence: i * 2n, payload: new Uint8Array() }))); } assert.equal(queued.droppedFrames, 1); assert.equal(queued.processOne()?.frame, 2n); assert.equal(queued.processOne()?.frame, 3n); for (let i = 0; i < MAX_DRAWS_PER_FRAME; i++) { /* quota constant is exercised by the server suite */ }
const fixtureDir = new URL("../fixtures/", import.meta.url); for (const name of readdirSync(fixtureDir).filter(n => n.startsWith("valid-") && n.endsWith(".hex"))) { const fixture = Buffer.from(readFileSync(new URL(name, fixtureDir), "utf8").trim(), "hex"); const message = decode(fixture); assert.deepEqual([...encode({ type: message.type, flags: message.flags ?? 0, sequence: message.sequence, objectId: message.objectId ?? 0n, payload: message.payload })], [...fixture]); } for (const name of readdirSync(fixtureDir).filter(n => n.startsWith("malformed-") && n.endsWith(".hex"))) assert.throws(() => decode(Buffer.from(readFileSync(new URL(name, fixtureDir), "utf8").trim(), "hex")));
console.log("TCW-PROTO-001_PASS independent TypeScript codec; shared fixture parity valid=11 malformed=11"); console.log("TCW-PROTO-002_PASS asserted codec, authentication, lifecycle, resource accounting, and queue policy; exhaustive supervisor matrix remains under review");
