import { WebSocketServer, WebSocket, type RawData } from "ws";
import { randomBytes } from "node:crypto";
import { authenticate, decode, encodeFrameAccepted, MAX_HELLO_BYTES, MAX_WEBSOCKET_BYTES, MirrorSession, MessageType, type Hello } from "./index.js";
function rawBytes(data: RawData): Buffer { return Buffer.concat((Array.isArray(data) ? data : [data]).map((part) => Buffer.from(part as any))); }
export class BridgeServer {
  readonly token = randomBytes(24).toString("hex"); private readonly server = new WebSocketServer({ host: "127.0.0.1", port: 0, maxPayload: MAX_WEBSOCKET_BYTES }); private controller: WebSocket | undefined; private readonly sessions = new Map<WebSocket, MirrorSession>(); private generation = 0n;
  constructor(private readonly allowedOrigin = "http://127.0.0.1:5173") {}
  async start(): Promise<number> { await new Promise<void>((resolve, reject) => { this.server.once("listening", resolve); this.server.once("error", reject); }); const address = this.server.address(); if (!address || typeof address === "string") throw new Error("ephemeral port unavailable"); this.server.on("connection", (socket, request) => { let authenticated = false; socket.on("message", (data, isBinary) => { try { const raw = rawBytes(data); if (!authenticated) { if (isBinary || raw.byteLength > MAX_HELLO_BYTES || this.controller) throw new Error("session unavailable"); const caps = authenticate(JSON.parse(raw.toString()) as Hello, this.token, this.allowedOrigin, request.headers.origin ?? ""); authenticated = true; this.controller = socket; this.generation++; this.sessions.set(socket, new MirrorSession(caps.sessionId)); socket.send(JSON.stringify(caps)); return; } if (socket.readyState !== WebSocket.OPEN || !isBinary) throw new Error("post-auth text rejected"); const message = decode(new Uint8Array(raw)); const session = this.sessions.get(socket); if (!session) throw new Error("session missing"); session.accept(message); if (message.type === MessageType.EndFrame) { const state = session.processOne(); if (!state) throw new Error("frame queue empty"); socket.send(encodeFrameAccepted(this.generation, state, session.lastAcceptedSequence, session.droppedFrames)); } } catch (error) { socket.close(authenticated ? 1002 : 1008, `protocol violation: ${(error as Error).message}`); } }); socket.once("close", () => { this.sessions.delete(socket); if (this.controller === socket) this.controller = undefined; }); }); return address.port; }
  async close(): Promise<void> { for (const client of this.server.clients) client.terminate(); await new Promise<void>((resolve) => this.server.close(() => resolve())); }
}
