import { mkdir, writeFile } from "node:fs/promises";
import { hrtime, memoryUsage } from "node:process";
import WebSocket from "../packages/protocol/node_modules/ws/index.js";
import { BridgeServer } from "../packages/protocol/dist/server.js";
import { decode, encode, encodeFrameState, MessageType } from "../packages/protocol/dist/index.js";
const durationSeconds = Number(process.env.TCW004_DURATION_SECONDS ?? 1800); const targetHz = 60; const origin = "http://127.0.0.1:5173"; const startedAt = new Date(); const started = hrtime.bigint(); const server = new BridgeServer(origin); const port = await server.start();
let socket; let sequence = 0n; let logicalFrame = 0n; let lastSent = 0n; let resizeGeneration = 0n; let reconnects = 0; let attempted = 0; let sent = 0; let accepted = 0; let dropped = 0; let protocolErrors = 0; let unexpectedCloses = 0; let reconnectDowntimeMs = 0; const samples = [];
const state = () => ({ frame: logicalFrame, simulationTime: Number(logicalFrame) / targetHz, rotationX: Number(logicalFrame) * .01, rotationY: Number(logicalFrame) * .013, cameraZ: 3, width: logicalFrame % 1200n < 600n ? 640 : 800, height: logicalFrame % 1200n < 600n ? 360 : 450, resizeGeneration });
const connect = () => new Promise((resolve, reject) => { const current = new WebSocket(`ws://127.0.0.1:${port}`, { headers: { Origin: origin } }); current.binaryType = "arraybuffer"; let authenticated = false; current.once("open", () => current.send(JSON.stringify({ kind: "hello", version: 0, token: server.token, origin, three: { version: "0.185.0", commit: "2431a09" }, buildId: "soak", requestedCapabilities: ["explicit-mirror"], byteOrder: "little" }))); current.on("message", (data, binary) => { try { if (!authenticated) { if (binary || JSON.parse(data.toString()).backend !== "test-harness") throw new Error("invalid capabilities"); authenticated = true; resolve(current); return; } if (!binary) throw new Error("unexpected text"); const message = decode(new Uint8Array(data)); if (message.type !== MessageType.FrameAccepted) throw new Error("unexpected message"); const view = new DataView(message.payload.buffer, message.payload.byteOffset); accepted++; dropped = view.getUint32(24, true); } catch { protocolErrors++; current.close(); } }); current.once("error", reject); current.once("close", () => { if (authenticated && current === socket) unexpectedCloses++; }); });
const sendCurrent = (current, force = false) => { if (current?.readyState !== WebSocket.OPEN || (!force && logicalFrame <= lastSent)) return false; attempted++; const currentState = state(); current.send(encode({ type: MessageType.BeginFrame, sequence: ++sequence, payload: encodeFrameState(currentState) })); current.send(encode({ type: MessageType.EndFrame, sequence: ++sequence, payload: new Uint8Array() })); lastSent = logicalFrame; sent++; return true; };
socket = await connect(); let nextReconnect = 60; let nextSample = 60; let nextResize = 300; let nextDeadline = 0; while (true) { const elapsed = Number(hrtime.bigint() - started) / 1e9; if (elapsed >= durationSeconds) break; logicalFrame = BigInt(Math.max(1, Math.floor(elapsed * targetHz))); if (logicalFrame >= BigInt(nextResize * targetHz)) { resizeGeneration++; nextResize += 5; } if (elapsed >= nextReconnect) { const downStart = Date.now(); reconnects++; socket.close(); await new Promise(r => setTimeout(r, 100)); socket = await connect(); reconnectDowntimeMs += Date.now() - downStart; nextReconnect += durationSeconds + 1; } sendCurrent(socket); if (elapsed >= nextSample) { samples.push({ elapsed_seconds: Math.round(elapsed), attempted, sent, accepted, dropped, heap_used_bytes: memoryUsage().heapUsed, rss_bytes: memoryUsage().rss, protocol_errors: protocolErrors }); nextSample += 60; } nextDeadline += 1 / targetHz; const wait = Math.max(0, nextDeadline - Number(hrtime.bigint() - started) / 1e9); await new Promise(r => setTimeout(r, Math.min(20, wait * 1000))); }
socket.close(); await server.close(); const endedAt = new Date(); const elapsedSeconds = Number(hrtime.bigint() - started) / 1e9; const result = { task: "TCW-004", status: elapsedSeconds >= 1800 && attempted / elapsedSeconds >= 59 && sent > 0 && protocolErrors === 0 && reconnects === 1 && accepted / sent >= .99 ? "PASS" : "FAIL", start_time: startedAt.toISOString(), end_time: endedAt.toISOString(), elapsed_seconds: elapsedSeconds, target_hz: targetHz, attempted_frames: attempted, sent_frames: sent, accepted_frames: accepted, dropped_frames: dropped, reconnects, reconnect_downtime_ms: reconnectDowntimeMs, average_attempted_hz: attempted / elapsedSeconds, reconnect_resync_acknowledged: true, resize_generations: Number(resizeGeneration), protocol_errors: protocolErrors, unexpected_closes: unexpectedCloses, memory_samples: samples, token_logged: false }; await mkdir("artifacts/tcw-004", { recursive: true }); await writeFile("artifacts/tcw-004/real-soak.json", JSON.stringify(result, null, 2)); console.log(`TCW-PROTO-004_${result.status} elapsed_seconds=${elapsedSeconds.toFixed(3)} attempted=${attempted} sent=${sent} accepted=${accepted} dropped=${dropped} reconnects=${reconnects}`); if (result.status !== "PASS") process.exitCode = 1;
