import { mkdir, writeFile } from "node:fs/promises";
import WebSocket from "../packages/protocol/node_modules/ws/index.js";
import { BridgeServer } from "../packages/protocol/dist/server.js";
import { decode, encode, encodeFrameState, MessageType } from "../packages/protocol/dist/index.js";

const durationSeconds = 1800; const intervalMs = 1000 / 60; const started = new Date(); const samples = []; const server = new BridgeServer("http://127.0.0.1:5173"); const port = await server.start(); let frame = 1n; let sequence = 0n; let resizeGeneration = 0n; let reconnects = 0; let accepted = 0; let drops = 0; let protocolErrors = 0; let client;
const state = () => ({ frame, simulationTime: Number(frame) / 60, rotationX: Number(frame) * .01, rotationY: Number(frame) * .013, cameraZ: 3, width: frame % 1200n < 600n ? 640 : 800, height: frame % 1200n < 600n ? 360 : 450, resizeGeneration });
const connect = () => new Promise((resolve, reject) => { const socket = new WebSocket(`ws://127.0.0.1:${port}`, { headers: { Origin: "http://127.0.0.1:5173" } }); socket.binaryType = "arraybuffer"; socket.once("open", () => socket.send(JSON.stringify({ kind: "hello", version: 0, token: server.token, origin: "http://127.0.0.1:5173", three: { version: "0.185.0", commit: "2431a09" }, buildId: "soak", requestedCapabilities: ["explicit-mirror"], byteOrder: "little" }))); socket.once("message", (data, binary) => { if (binary) return reject(new Error("capabilities was binary")); resolve(socket); }); socket.once("error", reject); socket.on("message", (data, binary) => { if (binary) { const message = decode(new Uint8Array(data)); if (message.type === MessageType.FrameAccepted) { accepted++; drops = new DataView(message.payload.buffer, message.payload.byteOffset).getUint32(24, true); } } }); socket.on("error", () => { protocolErrors++; }); });
client = await connect(); const timer = setInterval(() => { const current = state(); client.send(encode({ type: MessageType.BeginFrame, sequence: ++sequence, payload: encodeFrameState(current) })); client.send(encode({ type: MessageType.EndFrame, sequence: ++sequence, payload: new Uint8Array() })); if (frame % 300n === 0n) { resizeGeneration++; const payload = new Uint8Array(16); const view = new DataView(payload.buffer); view.setUint32(0, current.width, true); view.setUint32(4, current.height, true); view.setBigUint64(8, resizeGeneration, true); client.send(encode({ type: MessageType.Resize, sequence: ++sequence, payload })); } frame++; }, intervalMs);
const reconnectTimer = setTimeout(async () => { reconnects++; client.close(); await new Promise((resolve) => setTimeout(resolve, 100)); client = await connect(); }, 60_000);
const sampleTimer = setInterval(() => { samples.push({ elapsed_seconds: Math.round((Date.now() - started.getTime()) / 1000), logical_frame: Number(frame), accepted_frames: accepted, dropped_frames: drops, heap_used_bytes: process.memoryUsage().heapUsed, protocol_errors: protocolErrors }); }, 60_000);
await new Promise((resolve) => setTimeout(resolve, durationSeconds * 1000)); clearInterval(timer); clearTimeout(reconnectTimer); clearInterval(sampleTimer); client.close(); await server.close(); const ended = new Date(); const result = { task: "TCW-004", status: protocolErrors === 0 && frame >= 107000n ? "PASS" : "FAIL", start_time: started.toISOString(), end_time: ended.toISOString(), elapsed_seconds: (ended.getTime() - started.getTime()) / 1000, logical_frames: Number(frame), accepted_frames: accepted, dropped_frames: drops, reconnects, resize_generations: Number(resizeGeneration), protocol_errors: protocolErrors, memory_samples: samples, token_logged: false }; await mkdir("artifacts/tcw-004", { recursive: true }); await writeFile("artifacts/tcw-004/real-soak.json", JSON.stringify(result, null, 2)); console.log(`TCW-PROTO-004_${result.status} elapsed_seconds=${result.elapsed_seconds} logical_frames=${result.logical_frames} reconnects=${reconnects} dropped_frames=${drops}`);
